// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://koinluzxltubzxwdolzt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtvaW5sdXp4bHR1Ynp4d2RvbHp0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4MTgyMjksImV4cCI6MjA2NjM5NDIyOX0.tJoPy5HGxUMFh21AREn7Vc4DapV0oFiEGIDb2rHo3Pc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);